### ISSUE TITLE
SDK not building

### ISSUE THREAD

**Issue by ajazam** [awslabs/aws-sdk-rust#735]
### Describe the bug

Can't build the SDK using cargo build

### Expected Behavior

Cargo build to run successfully 

### Current Behavior

I get the following error

```
> error[E0599]: no method named `div_mod_floor` found for type `i128` in the current scope
  --> sdk/aws-smithy-types/src/date_time/mod.rs:75:54
     |
75   |         let (seconds, subsecond_nanos) = epoch_nanos.div_mod_floor(&NANOS_PER_SECOND);
     |            
```                                                          ^^^^^^^^^^^^^ help: there is a method with a similar name: `div_floor`


### Reproduction Steps

git clone https://github.com/awslabs/aws-sdk-rust.git
cd aws-sdk-rust
cargo build

### Possible Solution

I'm not sure what the problem is. It builds correctly inside windows 11 using rust 1.67. It does not build in ubuntu 22.04 with Rust 1. 1.67 inside WSL2.

### Additional Information/Context

_No response_

### Version

```text
I can't post the results of the above command. I get "There was an error creating your issue: body is too long(maximum is 65536 characters" when I click Submit new issue
```

### Environment details (OS name and version, etc.)

Windows 11 and Ubuntu 22.04 LTS (inside WSL)

**Comment by ajazam** [comment]
Never mind. I can't recreate this under Ubuntu running on real hardware. So the problem points to my WSL environment
